### ISSUE TITLE
Track performance of `turing_model`

### ISSUE THREAD

**Issue by storopoli** [TuringLang/TuringGLM.jl#47]
Thanks for the nice improvements, @devmotion. It’ll be great if we can track performance regression for TuringGLM (e.g. using a notebook similar to tutorials), but that can be done in a separate PR.

_Originally posted by @yebai in https://github.com/TuringLang/TuringGLM.jl/issues/45#issuecomment-1055540632_

**Comment by rikhuijzer** [comment]
Would pretty printing some outputs to a log be a solution or do we need something more fancy such as a static website or an automatic performance report comment? Static website is gonna be difficult since this repo already has Documenter in the gh-pages branch and automatic comment is gonna be annoying because bot comments are always annoying

**Comment by rikhuijzer** [comment]
Maybe we can add one issue about performance and automatically add comments to that issue with the benchmark results and a ref to the PR or to a commit on a branch. That way people can unsubscribe from the issue and not get notifications but still see results by clicking on the issue cross-ref. Also, the benchmark history is easily visible by scrolling through the issue comments.

**Comment by devmotion** [comment]
We use BenchmarkCI in KernelFunctions: https://github.com/JuliaGaussianProcesses/KernelFunctions.jl/pull/399
